---
title: Derecho Antidiscriminatorio
output:
    html_document:
        theme: flatly
        toc: TRUE
        toc_float: TRUE

---
# Bienvenida

Bienvenides al curso de capacitación online de "Derecho Antidiscrinatorio". Esta edición está preparada para ser cursada '100%' online, de acuedo a lo dispuesto por el [decreto 297/20](https://www.boletinoficial.gob.ar/detalleAviso/primera/227042/20200320).

En este sitio encontrarán el material y los enlaces necesarios para poder seguir el curso.


# Cronograma

El curso se desarrollará en seis clases virtuales, a través de la applicación [Zoom](https://zoom.us/) o si llegara a no funcionar como esperamos, vamos a [Jitsi](https://meet.jit.si/) que es de código abierto.

## Clase 1. Introducción

Introducción al programa. Algunos debates filosóficos sobre qué es la igualdad, y qué desigualdades deben ser mitigadas o reparadas. John Rawls: dos principios de Justicia, lotería natural y desigualdades sociales. Como mitigar o compensar la desigualdad. Ronald Dworkin: igualdad de recursos y suerte bruta y opcional. ¿Existe algo como el mérito? Elizabeth Andersen: Igualdad relacional y desigualdad de grupos. Grupos oprimidos versus opresores.

Aca las [diapositivas](https://cursoinadiclase1.netlify.app/)

Bibliografía

Al dar esta clase asuno que ningune ha leido previamente ningún texto. Si quieren leerlo aca están los textos. 

1. Queralt Lange, [capítulos 2 (Rawls)](https://drive.google.com/open?id=0B50ljTnhr79kUVRhc2E2TFphWnc) y [capítulo 4 (Dworkin)](https://drive.google.com/open?id=0B50ljTnhr79kdEZybzdoMlR5aVU).
2. Elizabeth Anderson, [Whats the point of equality?](https://drive.google.com/open?id=0B50ljTnhr79kRkd5MWQwMVNRUmM) (igualdad relacional).

## Clase 2. Igualdad como no discriminación


Igualdad como igualdad en iguales circunstancias. ¿Qué significa ello? Razonabilidad como no establecimiento de requisitos irrazonables. Ajuste de medios a fines. Análisis de estos fines y de las justificaciones. Igualdad individual vs. Igualdad de grupos.

Fallos 

- CSJN, [Caille](http://www.saij.gob.ar/corte-suprema-justicia-nacion-federal-ciudad-autonoma-buenos-aires-caille-eduardo-fa28000000-1928-10-26/123456789-000-0008-2ots-eupmocsollaf). 
- CSJN, [Arenzon](http://www.saij.gob.ar/corte-suprema-justicia-nacion-federal-ciudad-autonoma-buenos-aires-gabriel-dario-arenzon-estado-nacional-argentino-mrio-educacion-direccionnacional-sanidadescolar-amparo-fa84000170-1984-05-15/123456789-071-0004-8ots-eupmocsollaf).
- CSJN, [Reyes Aguilera](http://sjconsulta.csjn.gov.ar/sjconsulta/documentos/verDocumentoByIdLinksJSP.html?idDocumento=6323981).

Aca están las [diapositivas](https://cursoinadiclase2.netlify.app/)

Bibliografía

- Roberto Saba, Mas allá de la igualdad formal ante la ley, Siglo XXI Editores, 2016, [Cap 1 “Desigualdad estructural”](https://drive.google.com/open?id=0B50ljTnhr79kUWpFbWdHRXFfMzg).
- Gargarella, [Cómo no debería pensarse el derecho a la igualdad. Un análisis de las opiniones disidentes en el fallo Reyes Aguilera](http://seminariogargarella.blogspot.com/2007/09/cmo-no-debera-pensarse-el-derecho-la.html)

## Clase 3. Igualdad como no sometimiento, Categorías sospechosas


Diferencias entre grupos, mayoritarios vs. históricamente oprimidos. Qué hacer en casos de afectación a estos últimos. Análisis colectivo. Análisis de la discriminación en las normas o en los hechos, de particulares o del Estado, a través de políticas discriminatorias expresas o implícitas.

¿Qué son las categorías sospechosas? ¿Es necesaria una norma formal que establezca estas categorías? ¿Cuáles son?

- CSJN, Repetto, 
- CSJN, Hooft, 
- CSJN, Gottschau,
- CSJN, Gonzalez de Delgado
- CSJN, Z.J.J

Aca están las [diapositivas](https://cursoinadiclase3.netlify.app/).

- Roberto Saba, Mas allá de la igualdad formal ante la ley, Siglo XXI Editores, 2016, [Cap 2 “Igualdad, clases y clasificaciones. ¿Qué es lo sospechosos de las categorías sospechosas?”](https://drive.google.com/open?id=0B50ljTnhr79kZ2NUUlc2YUJIUFU).

## Clase 4. Igualdad como no sometimiento, Trato desigual


Teoría del trato desigual. Diferencia de trato de los particulares y del Estado. ¿Es necesario probar la intención de discriminar? ¿Es necesario que quien discrimina tenga odio irracional contra un grupo? Teoría de la discriminacion racional, estadística.

- CSJN, [Pellicori](https://drive.google.com/open?id=19PYCB6bdab7Tfksn1MlAjthW4AU5RXrA)
- CSJN, [Sisnero](https://drive.google.com/open?id=1Lbw4tK5LU8J4xZs0igV6Qkff1z3LP7MZ)


- USSC, [“Mc Donnel Douglas Coorp v. Green”](https://drive.google.com/open?id=1nkfPElCGGJaU3YIPCN5dR3AWlqiDPdWb),
- USSC, [“Hazelwood v. United States”](https://drive.google.com/open?id=1x7cQlXq4O79acwp4AwS1_19_pjATP_ZS)

Acá las [diapositivas](https://cursoinadiclase4.netlify.app/)

## Clase 5. Igualdad como no sometimiento. Impacto Desproporcionado

Teoría del impacto desproporcionado. Una política (pública o particular) que tiene un impacto desigual en diversos grupos. ¿Qué habrá que probar en este caso?

- USSC, [Griggs v. Duke Power](https://drive.google.com/open?id=0B50ljTnhr79kTzV2WXBiVVVWSVU).

- [Fitzpatrick vs. City of Atlanta](https://drive.google.com/open?id=0B50ljTnhr79kcVVUeEpjSVZDdVk).

- CSJN, Castillo

## Clase 6. Desigualdad de trato entre particulares

- CSJN, Alvarez c. Cencosud,

- CNCiv, sala J, sent. del 11/10/2006, “Hertzriken, Luciano y otro c. Sanfuentes Fernández, Magdalena s/Danos y perjuicios”.

- Caso de Emiliano Naranjo. Fallo CSJN, Dictamen PGN, Fallo Sala II Camara Federal de San Martín


- Roberto Saba, Mas allá de la igualdad formal ante la ley, Siglo XXI Editores, 2016, [Cap 3 “Igualdad de trato entre particulares”](https://drive.google.com/open?id=0B50ljTnhr79kRGpUWGhQb3JZelU).



